[build]
  command = "npm run build"
  publish = "build/"
  functions="functions"
  publish="build"
   
[dev]
  command = "svelte-kit dev"

[functions]
  directory = "netlify/functions"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"