[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
NETLIFY = "true"

[dev]
 command = "svelte-kit dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"